Sprint 18
CptWhisker/GoRoute pull request #1
Opened 2024-11-13 22:24 UTC by CptWhisker

Implemented code generation via OpenAPI and Swagger to integrate API communication into the project. Learned how to generate and utilize client code for the “Яндекс Расписаний” API, encapsulating it in the YandexScheduleService. Updated the MainScreenViewModel and MainScreen to handle API actions via generated code.

2024-11-14 17:54 UTC, protos17 requested changes

2024-11-14 17:54 UTC, protos17 commented on GoRoute/MainScreen/Model/MainScreenAction.swift
> +    }
Рекомендую выровнять нажав `cmd` + `i`

2024-11-14 17:54 UTC, protos17 commented on GoRoute/MainScreen/View/MainScreen.swift
> +                        action.performAction(on: viewModel)
Рекомендую `Task` указать здесь, а в вызовах внутри указать методы как `async` без `Task`

2024-11-14 17:54 UTC, protos17 commented on GoRoute/MainScreen/ViewModel/MainScreenViewModel.swift
> +final class MainScreenViewModel: ObservableObject {
Можно еще вместо `ObservableObject` использовать `@Observable` [статья](https://www.avanderlee.com/swiftui/observable-macro-performance-increase-observableobject/)

2024-11-14 17:54 UTC, protos17 commented on GoRoute/MainScreen/ViewModel/MainScreenViewModel.swift
> +        Task {
Рекомендую указывать метод как `async` без `Task`, а `Task` указывать в самом верхнем уровне вызова. В итоге `Task` будет указан только один раз у кнопки, а остальные вызовы до него будут `async`

2024-11-15 07:23 UTC, CptWhisker commented on GoRoute/MainScreen/View/MainScreen.swift
> +                        action.performAction(on: viewModel)
Выглядит логично, еще и код меньше дублируется

2024-11-15 07:34 UTC, CptWhisker commented on GoRoute/MainScreen/ViewModel/MainScreenViewModel.swift
> +final class MainScreenViewModel: ObservableObject {
Я так и хотел сделать, но у нас по ТЗ поддержка iOS 15+.
Не могу сказать насколько будет в данном случае оправданна поддержка двух версий через `if #avaliable` :(

2024-11-15 07:41 UTC, protos17 commented on GoRoute/MainScreen/ViewModel/MainScreenViewModel.swift
> +final class MainScreenViewModel: ObservableObject {
Согласен, нужно оставить. Просто информация на будущее

2024-11-15 08:03 UTC, CptWhisker commented
Замечания поправил, тесты постепенно буду тоже добавлять.

2024-11-15 17:57 UTC, protos17 approved these changes

2024-11-15 17:57 UTC, protos17 commented on GoRoute.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 18.0;
Если мы работаем от iOS 15+, то тут минимальную версию нужно 15 указать тогда

2024-11-15 17:57 UTC, protos17 commented on GoRoute/MainScreen/Model/MainScreenAction.swift
> +    var id: String { rawValue }
Надежнее для `id` использовать `UUID`, но строка тоже вполне допустима

2024-11-17 11:37 UTC, merged